<?php
/**
 * @file
 * Provides search suggestions when searching in the well.
 */

define('TING_AUTOCOMPLETE_SUGGESTIONS', 10);

/**
 * Implements hook_menu().
 */
function ting_search_autocomplete_menu() {
  $items = array();

  $items['ting/autocomplete/%'] = array(
    'title' => 'Ting search autocomplete',
    'description' => 'Returns a list of suggestions to use for autocompletion',
    'access arguments' => array('search content' ),
    'page callback' => 'ting_search_autocomplete',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'ting_search_autocomplete.pages.inc'
  );

  $items['admin/config/ting/autocomplete'] = array(
    'title' => 'Ting search autocomplete',
    'description' => 'Configure search autocomplete settings',
    'access arguments' => array('access administration pages'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_search_autocomplete_admin_form'),
    'file' => 'ting_search_autocomplete.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_flush_caches().
 */
function ting_search_autocomplete_flush_caches() {
  return array('cache_ting_search_autocomplete');
}

/**
 * Implements hook_form_alter().
 */
function ting_search_autocomplete_form_search_block_form_alter(&$form, &$form_state) {
  $suggestions_url = variable_get('ting_search_autocomplete_url', '');

  if (!empty($suggestions_url)) {
    drupal_add_library('system', 'ui.autocomplete');
    drupal_add_css(drupal_get_path('module', 'ting_search_autocomplete') . '/css/ting_search_autocomplete.css');
    drupal_add_js(drupal_get_path('module', 'ting_search_autocomplete') . '/js/ting_search_autocomplete.js');
  }
}
